-- Table: categories
DROP TABLE IF EXISTS categories;
CREATE TABLE IF NOT EXISTS categories (id INTEGER PRIMARY KEY NOT NULL, name TEXT NOT NULL);
INSERT INTO categories (id, name) VALUES (1, 'Owner');
INSERT INTO categories (id, name) VALUES (2, 'Celestial');
INSERT INTO categories (id, name) VALUES (3, 'Station');
INSERT INTO categories (id, name) VALUES (4, 'Material');
INSERT INTO categories (id, name) VALUES (5, 'Accessories');
INSERT INTO categories (id, name) VALUES (6, 'Ship');
INSERT INTO categories (id, name) VALUES (7, 'Module');
INSERT INTO categories (id, name) VALUES (8, 'Charge');
INSERT INTO categories (id, name) VALUES (9, 'Blueprint');
INSERT INTO categories (id, name) VALUES (10, 'Trading');
INSERT INTO categories (id, name) VALUES (11, 'Entity');
INSERT INTO categories (id, name) VALUES (14, 'Bonus');
INSERT INTO categories (id, name) VALUES (16, 'Skill');
INSERT INTO categories (id, name) VALUES (17, 'Commodity');
INSERT INTO categories (id, name) VALUES (18, 'Drone');
INSERT INTO categories (id, name) VALUES (20, 'Implant');
INSERT INTO categories (id, name) VALUES (22, 'Deployable');
INSERT INTO categories (id, name) VALUES (23, 'Starbase');
INSERT INTO categories (id, name) VALUES (24, 'Reaction');
INSERT INTO categories (id, name) VALUES (25, 'Asteroid');
INSERT INTO categories (id, name) VALUES (26, 'WorldSpace');
INSERT INTO categories (id, name) VALUES (29, 'Abstract');
INSERT INTO categories (id, name) VALUES (30, 'Apparel');
INSERT INTO categories (id, name) VALUES (32, 'Subsystem');
INSERT INTO categories (id, name) VALUES (34, 'Ancient Relics');
INSERT INTO categories (id, name) VALUES (35, 'Decryptors');
INSERT INTO categories (id, name) VALUES (39, 'Infrastructure Upgrades');
INSERT INTO categories (id, name) VALUES (40, 'Sovereignty Structures');
INSERT INTO categories (id, name) VALUES (41, 'Planetary Industry');
INSERT INTO categories (id, name) VALUES (42, 'Planetary Resources');
INSERT INTO categories (id, name) VALUES (43, 'Planetary Commodities');
INSERT INTO categories (id, name) VALUES (46, 'Orbitals');
INSERT INTO categories (id, name) VALUES (49, 'Placeables');
INSERT INTO categories (id, name) VALUES (53, 'Effects');
INSERT INTO categories (id, name) VALUES (54, 'Lights');
INSERT INTO categories (id, name) VALUES (59, 'Cells');
INSERT INTO categories (id, name) VALUES (63, 'Special Edition Assets');
INSERT INTO categories (id, name) VALUES (65, 'Structure');
INSERT INTO categories (id, name) VALUES (66, 'Structure Module');
INSERT INTO categories (id, name) VALUES (87, 'Fighter');
INSERT INTO categories (id, name) VALUES (91, 'SKINs');
INSERT INTO categories (id, name) VALUES (2100, 'Expert Systems');
INSERT INTO categories (id, name) VALUES (2107, 'Mining');
INSERT INTO categories (id, name) VALUES (2118, 'Personalization');
INSERT INTO categories (id, name) VALUES (350001, 'Infantry');
